name: Backend Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  # PASO 1: Construir y subir la imagen
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./laravel  # Asegúrate de que esta sea la ruta donde está tu Dockerfile
          push: true
          tags: kikee282/laravel-app:latest

  # PASO 2: Desplegar en la instancia
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            # Entramos a la carpeta y bajamos la NUEVA imagen
            cd ~/app
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull kikee282/laravel-app:latest
            
            # Recreamos los contenedores
            docker compose -f docker-compose.prod.yml up -d --force-recreate
            
            # Migraciones
            docker exec laravel_app_container php artisan migrate --force
            docker exec laravel_app_container php artisan db:seed