name: Backend Deploy Pipeline

on:
  push:
    branches:
      - main  # Asegúrate de que esta es la rama donde haces los push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            # 1. Login en Docker Hub
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            
            # 2. Descargar la versión más reciente de la imagen
            docker pull kikee282/laravel-app:latest
            
            # 3. Levantar el contenedor con el archivo de producción
            # Usamos -f para especificar el archivo y --force-recreate para refrescar
            docker-compose -f ~/app/docker-compose.prod.yml up -d --force-recreate
            
            # 4. Ejecutar migraciones automáticamente
            # Asegúrate de que el nombre del contenedor es exacto al de tu docker-compose.prod.yml
            docker exec laravel_app_container php artisan migrate --force