name: Backend CI/CD

on:
  push:
    branches:
    - "*"
    paths: ['laravel/**']

jobs:
  build-and-push:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull kikee282/laravel-app:latest
            docker-compose -f ~/app/docker-compose.prod.yml down
            docker-compose -f ~/app/docker-compose.prod.yml up -d
            docker exec laravel_app_container php artisan migrate --force